-- Drop the table if it already exists
DROP TABLE IF EXISTS patient;

-- Create the table
CREATE TABLE patient (
    id INT NOT NULL PRIMARY KEY IDENTITY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    gender VARCHAR(10) NOT NULL,
    diagnosis VARCHAR(100),
    treatment_plan TEXT,
    insurance_provider VARCHAR(100),
    admitted_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Insert 50 patient records
INSERT INTO patient (name, email, age, gender, diagnosis, treatment_plan, insurance_provider) VALUES
('Chloe Mills', 'chloe.mills@example.com', 28, 'Female', 'Asthma', 'Inhaled corticosteroids and rescue inhaler', 'Aetna'),
('Andrea May', 'andrea.may@example.com', 45, 'Female', 'Hypertension', 'ACE inhibitors and reduced sodium diet', 'Blue Cross'),
('Peter Harris', 'peter.harris@example.com', 60, 'Male', 'Osteoarthritis', 'NSAIDs and physical therapy', 'UnitedHealthcare'),
('Harry Russell', 'harry.russell@example.com', 52, 'Male', 'Migraines', 'Triptans and lifestyle adjustments', 'Cigna'),
('Frank Hodges', 'frank.hodges@example.com', 66, 'Male', 'Sleep Apnea', 'CPAP therapy', 'Humana'),
('Maria Paterson', 'maria.paterson@example.com', 34, 'Female', 'Type 1 Diabetes', 'Insulin injections and carb counting', 'Kaiser Permanente'),
('Isaac Moore', 'isaac.moore@example.com', 49, 'Male', 'IBS', 'Low-FODMAP diet and stress management', 'Aetna'),
('Vivian Ross', 'vivian.ross@example.com', 56, 'Female', 'Allergic Rhinitis', 'Antihistamines and allergen avoidance', 'Cigna'),
('Steven Black', 'steven.black@example.com', 43, 'Male', 'COPD', 'Bronchodilators and oxygen therapy', 'Blue Cross'),
('Leah Simmons', 'leah.simmons@example.com', 39, 'Female', 'Rheumatoid Arthritis', 'DMARDs and exercise', 'UnitedHealthcare'),
('Ethan Lewis', 'ethan.lewis@example.com', 62, 'Male', 'Chronic Kidney Disease', 'Dialysis and dietary adjustments', 'Humana'),
('Daniel Ortiz', 'daniel.ortiz@example.com', 50, 'Male', 'Chronic Back Pain', 'Physical therapy and muscle relaxants', 'Cigna'),
('Alan Foster', 'alan.foster@example.com', 48, 'Male', 'High Cholesterol', 'Statins and diet change', 'Aetna'),
('Kate Monroe', 'kate.monroe@example.com', 53, 'Female', 'Gastroesophageal Reflux', 'PPIs and avoiding trigger foods', 'Kaiser Permanente'),
('Connor Hayes', 'connor.hayes@example.com', 26, 'Male', 'Tonsillitis', 'Antibiotics and fluids', 'Blue Cross'),
('Mia Watson', 'mia.watson@example.com', 29, 'Female', 'Depression', 'Cognitive Behavioral Therapy', 'UnitedHealthcare'),
('Jacob Pierce', 'jacob.pierce@example.com', 63, 'Male', 'Parkinson’s Disease', 'Levodopa and physical therapy', 'Humana'),
('Julia Benson', 'julia.benson@example.com', 44, 'Female', 'Ovarian Cyst', 'Laparoscopy and hormonal therapy', 'Cigna'),
('Grace Patel', 'grace.patel@example.com', 38, 'Female', 'Anemia', 'Iron supplements and diet changes', 'Aetna'),
('Sophie Lane', 'sophie.lane@example.com', 35, 'Female', 'Insomnia', 'Sleep hygiene and melatonin', 'Blue Cross'),
('Lily Reed', 'lily.reed@example.com', 30, 'Female', 'PCOS', 'Lifestyle changes and metformin', 'UnitedHealthcare'),
('Alex Kim', 'alex.kim@example.com', 31, 'Non-Binary', 'ADHD', 'Behavioral therapy and stimulants', 'Cigna'),
('Andrea Evans', 'andrea.evans@example.com', 47, 'Female', 'Urinary Tract Infection', 'Antibiotics and hydration', 'Kaiser Permanente'),
('James Miller', 'james.miller@example.com', 59, 'Male', 'Prostate Enlargement', 'Alpha-blockers', 'Aetna'),
('Sarah Collins', 'sarah.collins@example.com', 40, 'Female', 'Thyroid Disorder', 'Levothyroxine', 'Blue Cross'),
('John Anderson', 'john.anderson@example.com', 51, 'Male', 'Gout', 'Allopurinol and low-purine diet', 'Cigna'),
('Leah Foster', 'leah.foster@example.com', 33, 'Female', 'Skin Allergy', 'Topical steroids and antihistamines', 'Humana'),
('Amy Scott', 'amy.scott@example.com', 29, 'Female', 'Infectious Mononucleosis', 'Rest and fluids', 'UnitedHealthcare'),
('Sam Grant', 'sam.grant@example.com', 55, 'Male', 'Sciatica', 'Physical therapy and anti-inflammatories', 'Kaiser Permanente'),
('Jan Lambert', 'jan.lambert@example.com', 42, 'Male', 'Bronchitis', 'Cough suppressants and rest', 'Blue Cross'),
('Simon Walsh', 'simon.walsh@example.com', 31, 'Male', 'Peptic Ulcer', 'PPI and antibiotics for H. pylori', 'Cigna'),
('Angela Knox', 'angela.knox@example.com', 36, 'Female', 'Gallstones', 'Surgery (cholecystectomy)', 'Humana'),
('Vanessa Lambert', 'vanessa.lambert@example.com', 37, 'Female', 'Sinusitis', 'Nasal spray and antibiotics', 'Aetna'),
('Ava Wallace', 'ava.wallace@example.com', 41, 'Female', 'Pneumonia', 'Antibiotics and rest', 'Blue Cross'),
('Henry Scott', 'henry.scott@example.com', 61, 'Male', 'Liver Cirrhosis', 'Lifestyle changes and monitoring', 'Kaiser Permanente'),
('Brian Ellis', 'brian.ellis@example.com', 28, 'Male', 'ACL Tear', 'Surgery and physical therapy', 'UnitedHealthcare'),
('Emma Walker', 'emma.walker@example.com', 33, 'Female', 'UTI', 'Antibiotics and hydration', 'Cigna'),
('Dylan Clark', 'dylan.clark@example.com', 34, 'Male', 'Allergic Dermatitis', 'Topical creams', 'Humana'),
('Madison Young', 'madison.young@example.com', 22, 'Female', 'Iron Deficiency Anemia', 'Iron tablets and diet', 'Blue Cross'),
('Ryan Cooper', 'ryan.cooper@example.com', 39, 'Male', 'Burn Injury', 'Wound care and antibiotics', 'Aetna'),
('Eric Holmes', 'eric.holmes@example.com', 46, 'Male', 'Glaucoma', 'Eye drops and surgery', 'Cigna'),
('Bella Shaw', 'bella.shaw@example.com', 26, 'Female', 'Conjunctivitis', 'Antibiotic drops', 'Kaiser Permanente'),
('Jack Stewart', 'jack.stewart@example.com', 40, 'Male', 'Fractured Arm', 'Cast and rest', 'Humana'),
('Emily King', 'emily.king@example.com', 25, 'Female', 'Anxiety Disorder', 'SSRIs and therapy', 'UnitedHealthcare'),
('Owen Barrett', 'owen.barrett@example.com', 38, 'Male', 'Obesity', 'Diet plan and exercise regimen', 'Aetna'),
('Riley Dean', 'riley.dean@example.com', 30, 'Non-Binary', 'Bipolar Disorder', 'Mood stabilizers and counseling', 'Blue Cross'),
('Leo Grant', 'leo.grant@example.com', 68, 'Male', 'Heart Failure', 'Beta-blockers and diuretics', 'Kaiser Permanente'),
('Ava Daniels', 'ava.daniels@example.com', 27, 'Female', 'Chickenpox', 'Rest and antiviral medication', 'Cigna'),
('Sean Brooks', 'sean.brooks@example.com', 44, 'Male', 'Food Poisoning', 'IV fluids and antibiotics', 'Humana');
